FROM node:20-bookworm-slim

RUN apt-get update && \
  apt-get install -y --no-install-recommends procps

WORKDIR /app

ADD package.json ./

RUN corepack enable

RUN pnpm install

USER node

EXPOSE 5173
EXPOSE 4173