FROM python:3.12.3-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps 

RUN addgroup --gid 1000 ubuntu
RUN useradd -lm -u 1000 -g 1000 ubuntu
USER ubuntu

WORKDIR /app

ADD requirements.txt .
RUN pip install -r requirements.txt